before_script:
  - apk add git
  - apk add openssh
  - apk add openssh-client
  - apk add curl
deploy_staging:
  image: node:12-alpine
  type: deploy
  script:
    - branchname=`echo "${CI_COMMIT_BRANCH}" | sed 's/feature\///g'`
    - curl -o .env.development ${DEVENV}
    - mkdir build
    - npm cache clean --force
    -  rm -rf node_modules
    - export NODE_OPTIONS=--max_old_space_size=8096
    - npm install
    - echo "*" > .eslintignore
    - npm run build:dev
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$KEY" | tr -d '\r' | ssh-add -
    - mv build $branchname
    - ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER rm -rf /$USERNAME/react-deploy/projects/$branchname
    - scp -o StrictHostKeyChecking=no -r ./$branchname $USERNAME@$SERVER:/$USERNAME/react-deploy/projects/
    - ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER 'docker exec -i nginx sh /scripts/generate-config.sh'
  only:
    - /^feature/.*$/