before_script:
  - apk add git
  - apk add openssh-client
  # - apt-get install nodejs npm
  # - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  # - eval $(ssh-agent -s)
  # - ssh-add <(echo "$SSH_PRIVATE_KEY")
  # - mkdir -p ~/.ssh
  # - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
deploy_staging:
  image: node:12-alpine
  type: deploy
  # environment:
  #   name: staging
  #   url: example.com
  script:
    - npm install
    - npm run build:dev
    # - ssh root@example.com "cd var/www/ && git checkout master && git pull origin master && exit"
  only:
    - /^feature/.*$/