cache:
  key: SITA-FE-V1
  paths:
    - node_modules/
  policy: pull-push
before_script:
  - apk add git
  - apk add openssh
  - apk add openssh-client
  - apk add curl
deploy_staging:
  image: node:12-alpine
  type: deploy
  script:
    - branchname=`echo "${CI_COMMIT_BRANCH}" | sed 's/autobuild\///g'`
    - curl -o .env.development ${DEVENV}
    - mkdir build
    - export NODE_OPTIONS=--max_old_space_size=8096
    - npm install
    - echo "*" > .eslintignore
    - npm run build:dev
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$KEY" | tr -d '\r' | ssh-add -
    - mv build $branchname
    - tar cvf $branchname.tar $branchname
    - ssh -o StrictHostKeyChecking=no -p 2222 $USERNAME@$SERVER rm -rf /$DEPLOY_PATH/react-deploy/projects/$branchname
    - scp -o StrictHostKeyChecking=no -P 2222 -r ./$branchname.tar $USERNAME@$SERVER:/$DEPLOY_PATH/react-deploy/projects/
    - ssh -o StrictHostKeyChecking=no -p 2222 $USERNAME@$SERVER tar xf /$DEPLOY_PATH/react-deploy/projects/$branchname.tar --directory /$DEPLOY_PATH/react-deploy/projects
    - ssh -o StrictHostKeyChecking=no -p 2222 $USERNAME@$SERVER rm /$DEPLOY_PATH/react-deploy/projects/$branchname.tar
    - curl login.sita.grappus.com/reload
  only:
    - /^autobuild/.*$/
